paths:
  /api/products?:
    get:
      summary: Obtener los productos
      parameters:
        - name: query
          in: query
          description: Objeto clave valor para filtrar productos, ejemplo  "category":"consoles"
          required: false
          schema:
            type: json
        - name: limit
          in: query
          description: Numero que limita la cantidad de productos devueltos
          required: false
          schema:
            type: Number
        - name: page
          in: query
          description: Numero de la pagina a la que se quiere acceder
          required: false
          schema:
            type: Number
        - name: sort
          in: query
          description: Numero que indica el orden en el que se muestran los productos
          required: false
          schema:
            type: Number
      tags:
        - Productos
      responses:
        "200":
          description: Los productos se entregaron satisfactoriamente.
        "500":
          description: Error de servidor.
  /api/products/{pid}:
    get:
      summary: Obtener producto por ID
      parameters:
        - in: path
          name: pid
          description: ID del producto a buscar
          required: true
          schema:
            type: string
      tags:
        - Productos
      responses:
        "200":
          description: El producto se entrego satisfactoriamente.
        "404":
          description: Producto no encontrado.
        "500":
          description: Error de servidor.
  /api/products:
    post:
      summary: Crear un producto
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
            example:
              title: Plastation 5
              description: Consola de ultima gama de Plastation
              code: PL5
              price: 300000
              status: true
              stock: 360
              category: consoles
              thumbnails: ["https://www.images.google.com/"]
              owner: email@gmail.com
        description: Caracteristicas del producto a agregar
        required: true
      tags:
        - Productos
      responses:
        "200":
          description: El producto se creo satisfactoriamente.

        "500":
          description: Error de servidor.
  /api/products/{pid}/:
    put:
      summary: Actualizar producto por ID
      parameters:
        - in: path
          name: pid
          description: ID del producto a buscar
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
            example:
              category: consoles
      tags:
        - Productos
      responses:
        "200":
          description: El producto se actualizo satisfactoriamente.
        "404":
          description: Producto no encontrado.
        "500":
          description: Error de servidor.
  /api/products//{pid}/:
    delete:
      summary: Eliminar producto por ID
      parameters:
        - in: path
          name: pid
          description: ID del producto a buscar
          required: true
          schema:
            type: string
      tags:
        - Productos
      responses:
        "200":
          description: El producto se elimino satisfactoriamente.
        "404":
          description: Producto no encontrado.
        "500":
          description: Error de servidor.

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID autogenerado
        title:
          type: string
          description: Titulo del producto
        description:
          type: string
          description: Descripcion del producto
        code:
          type: string
          description: Codigo identificador del producto
        price:
          type: Number
          description: Precio del producto
        status:
          type: Boolean
          description: Indica si el producto esta disponible para vender
        stock:
          type: Number
          description: Cantidad de productos para vender
        category:
          type: string
          description: Categoria a la que pertenece el producto
        thumbnails:
          type: Array
          description: Arreglo de rutas de imagenes del producto
        owner:
          type: string
          description: Creador del producto
